server:
  port: 8080
spring:
  application.name: ${APPLICATION_NAME:border-state-collector}
  datasource:
    url: ${DATASOURCE_URL:}
    username: ${POSTGRES_USER:}
    password: ${POSTGRES_PASSWORD:}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db/changelog/master.yaml
    default-schema: public
feign:
  client:
    config:
      default:
        loggerLevel: basic

border-waiting-area:
  scheduler:
    data-collection:
      checkpoints-update: ${CHECKPOINTS_UPDATE:86400000}
      states-update: ${STATES_UPDATE:15000}
  bot:
    url: ${BORDER_WAITING_AREA_URL:http://host.docker.internal:8088}