package info.mastera.model;

public enum QueueType {
    TRUCK_LIVE_QUEUE,
    TRUCK_PRIORITY,
    TRUCK_GPK,
    BUS_LIVE_QUEUE,
    BUS_PRIORITY,
    CAR_LIVE_QUEUE,
    CAR_PRIORITY,
    MOTORCYCLE_LIVE_QUEUE,
    MOTORCYCLE_PRIORITY
}
