#!/usr/bin/env sh

source .env

docker rm border-state-collector-app

docker build -t border-state-collector-app -f app/Dockerfile ../

docker run -p 8080:8080 \
           --env-file .env \
           -e DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/${POSTGRES_DB} \
           --name border-state-collector-app \
           -d border-state-collector-app