#!/usr/bin/env sh

source .env

docker rm border-state-collector-app

docker build -t border-state-collector-app -f app/Dockerfile ../

docker run --env-file .env \
  --name border-state-collector-app \
  -d border-state-collector-app
