version: '3.8'
name: local_network
services:

  border-state-collector-app:
    container_name: border-state-collector-app
    build:
      context: ../
      dockerfile: ./docker/app/Dockerfile
    env_file:
      - ./.env
