#!/usr/bin/env sh

docker run -p 5432:5432 \
           --env-file .env \
           -v border-state-collector-postgres:/var/lib/postgresql/data \
           --name border-state-collector-postgres \
           -d postgres:15.1-alpine
