version: '3'

services:
  prometheus:
    image: prom/prometheus:v3.4.2
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  node-exporter:
    image: prom/node-exporter:v1.9.1
    ports:
      - "9100:9100"

  grafana:
    image: grafana/grafana:12.0.2
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:
